### ISSUE TITLE
question

### ISSUE THREAD

**Issue by acyc070** [yquake2/yquake2remaster#25]
software render has a little vertex snapping like ps1 shown in this video:
https://github.com/yquake2/yquake2remaster/assets/112773735/4b434cba-e0c0-4920-9bf6-92d94ee0217b
i'm interested what EXACT line(s) of software rendering code controls this

**Comment by acyc070** [comment]
why this vertex snapping affects only md2 file but world geometry doesn't?

**Comment by 0lvin** [comment]
Maps and embedded objects, e.g. fan, door are rendered by render path, where all animation are calculated by current state and time.

All models are rendered with different render path based on linear interpolation for vertex points of current and previous frame.

Look to https://fabiensanglard.net/quake2/quake2_software_renderer.php for more info.

**Comment by acyc070** [comment]
answer my question about line(s)

**Comment by acyc070** [comment]
i'm not too good in programming, just show screenshots

**Comment by 0lvin** [comment]
Could you please share more information what do you want implement or change?

**Comment by acyc070** [comment]
strength of this snapping to be more like ps1

**Comment by Yamagi** [comment]
If I understand you right you are asking about lerping. Quake distinguishes between two types of models:

One is the world model, so to say the map itself defined in the .bsp file. The world model is static, it has no animations or movements and cannot be altered in any way. Therefore the world model can be rendered with fixed coordinates which never change.

The other one are alias models. So to say the "models", everything which is not part of the map itself. Alias models are dynamic. They can appear or disappear at any time, they can have animations, etc.

The problem is, that Quake is rather old and has frame based animations. In contrast to more modern games which use vectors, mostly called bones. Most animations have 10 FPS. Since the renderer runs (way) faster, these 10 animation frames per second must be interpolated on X renderer frames per second. This interpolation is called lerping. Since Quake II has rather low details, the math isn't perfect and the internal coordination system is of low resolution lerping leads to error. These are the typical "woppeling" which can be seen on (nearly) all models.

For the soft renderer the lerping implementation starts here: https://github.com/yquake2/yquake2remaster/blob/master/src/client/refresh/soft/sw_alias.c#L908 `R_AliasSetUpLerpData()` calculates the change to the coordinates and `R_AliasPreparePoints` applies them. `R_AliasPreparePoints()` also does other transformations, like scaling into the right perspective. 

It's easier to understand with the GL renderers. With OpenGL you pass the coordinates to the API and it does all the magic, the soft renderer must do it by itself. An educated guess is that the PS1 had a worse lerping implementation to save CPU cycles.

**Comment by 0lvin** [comment]
Look like ps1 has also issues with textures https://youtu.be/x8TO-nrUtSI so texture coordinates s,t should be also rounded in some way in [R_ProcessLeftEdge](https://github.com/yquake2/yquake2remaster/blob/master/src/client/refresh/soft/sw_polyset.c#L787).
