### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by acyc070** [yquake2/yquake2remaster#7]
What kind of code is responsible for the FPS of model animations?

**Comment by 0lvin** [comment]
Do you want to render model animation faster than default ~14fps?

**Comment by acyc070** [comment]
yes

**Comment by acyc070** [comment]
in what line of code can this be changed?

**Comment by 0lvin** [comment]
It's hard-coded in game logic, look to example of change [weapon change animation](https://github.com/yquake2/yquake2/pull/1031/files)

**Comment by 0lvin** [comment]
Where are you looking to player model? Game shows player model only in multiplayer model preview menu.

If you like to change animation speed in preview menu, look to [PlayerConfig_AnimateModel](https://github.com/yquake2/yquake2remaster/blob/master/src/client/menu/menu.c).

**Comment by acyc070** [comment]
"Where are you looking to player model?" In thirdperson

**Comment by 0lvin** [comment]
Player logic is implemented in [g_setclientframe](https://github.com/yquake2/yquake2/blob/master/src/game/player/view.c)

**Comment by Yamagi** [comment]
At least with the normal non-remastered gamedata you will run into issues with animation granularity. The game is build around a fixed framerate of 10 FPS. The gamecode is called 10 times a second, at every call animations are forwarded by one frame. The renderer calculates intermediated steps between the animation frames to scatter them over the render frames, make them somewhat more smooth but also adding this "wobbling" typical for Quake and Quake II based games.

You can see in the multiplayer menu what happens if no intermediate steps are calculated. The player model preview stutters, because it's rendered at it's native 10 FPS.

There are two ways to increase animation speed, both aren't optimal:

* Call the game more often. With the non-remastered game library that will very likely break a lot of things. It might be worth to gave a look what Nightdive did to support 40 calls a second: https://github.com/id-Software/quake2-rerelease-dll/ Currently the remastered game library cannot be used with YQ2, neither with the normal nor the remastered version.

* Skip or combine animation frames. That's what `g_swap_speed`. It's rather easy to implement, but the price are even more "stuttering" animations and more wobbeling.

The correct solution would be to port the game (the code and all assets) to more modern bone based animations like the MD5 model format has. But even Nightdive opted to not to do it, because it's a lot of work with little gain as long as you don't fiddle with animation speed.
